### ISSUE TITLE
Aggiungere pulsante invio Question sulla pagina Q&A

### ISSUE THREAD

**Issue by basteran** [Bludnec/Tesi-di-laurea#2]
Sulla pagina di Q&A, quando si interroga il modello, manca un pulsante per inviare la domanda al backend. La risposta conterrà la "Answer" da mettere nel campo associato.

Allego screenshot per intenderci, il pulsante potrebbe essere aggiunto nella zona rossa:
![image](https://user-images.githubusercontent.com/27162097/211525004-18f33162-a65c-42d9-abd5-04582ec5114b.png)

**Comment by Bludnec** [comment]
Aggiunto pulsante.
Pe ora stampa su console il valore della textarea 'Question' della sezione Q&A.
